# Derived from LandSandBoat (https://github.com/LandSandBoat/server),
# GNU General Public License v3.0; this file is GPL-3.0 as well. See
# tools/gen_ffxi_lsb_tables.py for the exact source files read.
"""GENERATED -- do not edit. `python tools/gen_ffxi_lsb_tables.py`.

Wire layout and char_points mapping for the FFXI currency packets,
parsed straight out of LandSandBoat's own s2c builders so that neither is
transcribed by hand. See the generator's docstring for why.

Each PACKETS entry:
  size    total PacketData bytes, EXCLUDING the 4-byte GP_SERV_HEADER
  fields  ordered [(name, kind, offset, ctype, extra)] where extra is the
          array length for 'array' and (shift, bits) for 'bits'
  columns {field: char_points column}
  computed {field: the C++ expression} -- NOT column-backed, never imported
"""

PACKETS = {
    "0x113": {
        "class": "GP_SERV_COMMAND_CURRENCIES_1",
        "size": 248,
        "fields": [
            ("conquest_points_sandoria", "scalar", 0, "int32_t", None, 4),
            ("conquest_points_bastok", "scalar", 4, "int32_t", None, 4),
            ("conquest_points_windurst", "scalar", 8, "int32_t", None, 4),
            ("beastmans_seals_stored", "scalar", 12, "uint16_t", None, 2),
            ("kindreds_seals_stored", "scalar", 14, "uint16_t", None, 2),
            ("kindreds_crests_stored", "scalar", 16, "uint16_t", None, 2),
            ("high_kindreds_crests_stored", "scalar", 18, "uint16_t", None, 2),
            ("sacred_kindreds_crests_stored", "scalar", 20, "uint16_t", None, 2),
            ("ancient_beastcoins_stored", "scalar", 22, "uint16_t", None, 2),
            ("valor_points", "scalar", 24, "uint16_t", None, 2),
            ("scylds", "scalar", 26, "uint16_t", None, 2),
            ("guild_points_fishing", "scalar", 28, "int32_t", None, 4),
            ("guild_points_woodworking", "scalar", 32, "int32_t", None, 4),
            ("guild_points_smithing", "scalar", 36, "int32_t", None, 4),
            ("guild_points_goldsmithing", "scalar", 40, "int32_t", None, 4),
            ("guild_points_weaving", "scalar", 44, "int32_t", None, 4),
            ("guild_points_leathercraft", "scalar", 48, "int32_t", None, 4),
            ("guild_points_bonecraft", "scalar", 52, "int32_t", None, 4),
            ("guild_points_alchemy", "scalar", 56, "int32_t", None, 4),
            ("guild_points_cooking", "scalar", 60, "int32_t", None, 4),
            ("cinders", "scalar", 64, "int32_t", None, 4),
            ("synergy_fewell_fire", "scalar", 68, "uint8_t", None, 1),
            ("synergy_fewell_ice", "scalar", 69, "uint8_t", None, 1),
            ("synergy_fewell_wind", "scalar", 70, "uint8_t", None, 1),
            ("synergy_fewell_earth", "scalar", 71, "uint8_t", None, 1),
            ("synergy_fewell_lightning", "scalar", 72, "uint8_t", None, 1),
            ("synergy_fewell_water", "scalar", 73, "uint8_t", None, 1),
            ("synergy_fewell_light", "scalar", 74, "uint8_t", None, 1),
            ("synergy_fewell_dark", "scalar", 75, "uint8_t", None, 1),
            ("ballista_points", "scalar", 76, "int32_t", None, 4),
            ("fellow_points", "scalar", 80, "int32_t", None, 4),
            ("chocobucks_sandoria_team", "scalar", 84, "uint16_t", None, 2),
            ("chocobucks_bastok_team", "scalar", 86, "uint16_t", None, 2),
            ("chocobucks_windurst_team", "scalar", 88, "uint16_t", None, 2),
            ("daily_tally", "scalar", 90, "uint16_t", None, 2),
            ("research_marks", "scalar", 92, "int32_t", None, 4),
            ("wizened_tunnel_worms", "scalar", 96, "uint8_t", None, 1),
            ("wizened_morion_worms", "scalar", 97, "uint8_t", None, 1),
            ("wizened_phantom_worms", "scalar", 98, "uint8_t", None, 1),
            ("unknown67", "scalar", 99, "uint8_t", None, 1),
            ("moblin_marbles", "scalar", 100, "int32_t", None, 4),
            ("infamy", "scalar", 104, "uint16_t", None, 2),
            ("prestige", "scalar", 106, "uint16_t", None, 2),
            ("legion_points", "scalar", 108, "int32_t", None, 4),
            ("sparks_of_eminence", "scalar", 112, "int32_t", None, 4),
            ("shining_stars", "scalar", 116, "int32_t", None, 4),
            ("imperial_standing", "scalar", 120, "int32_t", None, 4),
            ("assault_points_l_sanctum", "scalar", 124, "int32_t", None, 4),
            ("assault_points_mjtg", "scalar", 128, "int32_t", None, 4),
            ("assault_points_l_cavern", "scalar", 132, "int32_t", None, 4),
            ("assault_points_periqia", "scalar", 136, "int32_t", None, 4),
            ("assault_points_ilrusi_atoll", "scalar", 140, "int32_t", None, 4),
            ("tokens", "scalar", 144, "int32_t", None, 4),
            ("zeni", "scalar", 148, "int32_t", None, 4),
            ("jettons", "scalar", 152, "int32_t", None, 4),
            ("therion_ichor", "scalar", 156, "int32_t", None, 4),
            ("allied_notes", "scalar", 160, "int32_t", None, 4),
            ("copper_aman_vouchers_stored", "scalar", 164, "uint16_t", None, 2),
            ("login_points", "scalar", 166, "uint16_t", None, 2),
            ("cruor", "scalar", 168, "int32_t", None, 4),
            ("resistance_credits", "scalar", 172, "int32_t", None, 4),
            ("dominion_notes", "scalar", 176, "int32_t", None, 4),
            ("echelon_battle_trophies_5th", "scalar", 180, "uint8_t", None, 1),
            ("echelon_battle_trophies_4th", "scalar", 181, "uint8_t", None, 1),
            ("echelon_battle_trophies_3rd", "scalar", 182, "uint8_t", None, 1),
            ("echelon_battle_trophies_2nd", "scalar", 183, "uint8_t", None, 1),
            ("echelon_battle_trophies_1st", "scalar", 184, "uint8_t", None, 1),
            ("cave_conservation_points", "scalar", 185, "uint8_t", None, 1),
            ("imperial_army_id_tags", "scalar", 186, "uint8_t", None, 1),
            ("op_credits", "scalar", 187, "uint8_t", None, 1),
            ("traverser_stones", "scalar", 188, "int32_t", None, 4),
            ("voidstones", "scalar", 192, "int32_t", None, 4),
            ("kupofrieds_corundums", "scalar", 196, "int32_t", None, 4),
            ("moblin_pheromone_sacks", "scalar", 200, "uint8_t", None, 1),
            ("unknownCD", "scalar", 201, "uint8_t", None, 1),
            ("rems_tale_chapters_1_stored", "scalar", 202, "uint8_t", None, 1),
            ("rems_tale_chapters_2_stored", "scalar", 203, "uint8_t", None, 1),
            ("rems_tale_chapters_3_stored", "scalar", 204, "uint8_t", None, 1),
            ("rems_tale_chapters_4_stored", "scalar", 205, "uint8_t", None, 1),
            ("rems_tale_chapters_5_stored", "scalar", 206, "uint8_t", None, 1),
            ("rems_tale_chapters_6_stored", "scalar", 207, "uint8_t", None, 1),
            ("rems_tale_chapters_7_stored", "scalar", 208, "uint8_t", None, 1),
            ("rems_tale_chapters_8_stored", "scalar", 209, "uint8_t", None, 1),
            ("rems_tale_chapters_9_stored", "scalar", 210, "uint8_t", None, 1),
            ("rems_tale_chapters_10_stored", "scalar", 211, "uint8_t", None, 1),
            ("bloodshed_plans_stored", "bits", 212, "uint64_t", (0, 9), 8),
            ("umbrage_plans_stored", "bits", 212, "uint64_t", (9, 9), 8),
            ("ritualistic_plans_stored", "bits", 212, "uint64_t", (18, 9), 8),
            ("tutelary_plans_stored", "bits", 212, "uint64_t", (27, 9), 8),
            ("primacy_plans_stored", "bits", 212, "uint64_t", (36, 9), 8),
            ("unused", "bits", 212, "uint64_t", (45, 19), 8),
            ("reclamation_marks", "scalar", 220, "uint16_t", None, 2),
            ("padding00", "scalar", 222, "uint16_t", None, 2),
            ("unity_accolades", "scalar", 224, "int32_t", None, 4),
            ("fire_crystals_stored", "scalar", 228, "uint16_t", None, 2),
            ("ice_crystals_stored", "scalar", 230, "uint16_t", None, 2),
            ("wind_crystals_stored", "scalar", 232, "uint16_t", None, 2),
            ("earth_crystals_stored", "scalar", 234, "uint16_t", None, 2),
            ("lightning_crystals_stored", "scalar", 236, "uint16_t", None, 2),
            ("water_crystals_stored", "scalar", 238, "uint16_t", None, 2),
            ("light_crystals_stored", "scalar", 240, "uint16_t", None, 2),
            ("dark_crystals_stored", "scalar", 242, "uint16_t", None, 2),
            ("deeds", "scalar", 244, "uint16_t", None, 2),
            ("padding01", "scalar", 246, "uint16_t", None, 2),
        ],
        "columns": {
            "conquest_points_sandoria": "sandoria_cp",
            "conquest_points_bastok": "bastok_cp",
            "conquest_points_windurst": "windurst_cp",
            "beastmans_seals_stored": "beastman_seal",
            "kindreds_seals_stored": "kindred_seal",
            "kindreds_crests_stored": "kindred_crest",
            "high_kindreds_crests_stored": "high_kindred_crest",
            "sacred_kindreds_crests_stored": "sacred_kindred_crest",
            "ancient_beastcoins_stored": "ancient_beastcoin",
            "valor_points": "valor_point",
            "scylds": "scyld",
            "guild_points_fishing": "guild_fishing",
            "guild_points_woodworking": "guild_woodworking",
            "guild_points_smithing": "guild_smithing",
            "guild_points_goldsmithing": "guild_goldsmithing",
            "guild_points_weaving": "guild_weaving",
            "guild_points_leathercraft": "guild_leathercraft",
            "guild_points_bonecraft": "guild_bonecraft",
            "guild_points_alchemy": "guild_alchemy",
            "guild_points_cooking": "guild_cooking",
            "cinders": "cinder",
            "synergy_fewell_fire": "fire_fewell",
            "synergy_fewell_ice": "ice_fewell",
            "synergy_fewell_wind": "wind_fewell",
            "synergy_fewell_earth": "earth_fewell",
            "synergy_fewell_lightning": "lightning_fewell",
            "synergy_fewell_water": "water_fewell",
            "synergy_fewell_light": "light_fewell",
            "synergy_fewell_dark": "dark_fewell",
            "ballista_points": "ballista_point",
            "fellow_points": "fellow_point",
            "chocobucks_sandoria_team": "chocobuck_sandoria",
            "chocobucks_bastok_team": "chocobuck_bastok",
            "chocobucks_windurst_team": "chocobuck_windurst",
            "research_marks": "research_mark",
            "wizened_tunnel_worms": "tunnel_worm",
            "wizened_morion_worms": "morion_worm",
            "wizened_phantom_worms": "phantom_worm",
            "moblin_marbles": "moblin_marble",
            "infamy": "infamy",
            "prestige": "prestige",
            "legion_points": "legion_point",
            "sparks_of_eminence": "spark_of_eminence",
            "shining_stars": "shining_star",
            "imperial_standing": "imperial_standing",
            "assault_points_l_sanctum": "leujaoam_assault_point",
            "assault_points_mjtg": "mamool_assault_point",
            "assault_points_l_cavern": "lebros_assault_point",
            "assault_points_periqia": "periqia_assault_point",
            "assault_points_ilrusi_atoll": "ilrusi_assault_point",
            "tokens": "nyzul_isle_assault_point",
            "zeni": "zeni_point",
            "jettons": "jetton",
            "therion_ichor": "therion_ichor",
            "allied_notes": "allied_notes",
            "copper_aman_vouchers_stored": "aman_vouchers",
            "login_points": "login_points",
            "cruor": "cruor",
            "resistance_credits": "resistance_credit",
            "dominion_notes": "dominion_note",
            "echelon_battle_trophies_5th": "fifth_echelon_trophy",
            "echelon_battle_trophies_4th": "fourth_echelon_trophy",
            "echelon_battle_trophies_3rd": "third_echelon_trophy",
            "echelon_battle_trophies_2nd": "second_echelon_trophy",
            "echelon_battle_trophies_1st": "first_echelon_trophy",
            "cave_conservation_points": "cave_points",
            "imperial_army_id_tags": "id_tags",
            "op_credits": "op_credits",
            "voidstones": "voidstones",
            "kupofrieds_corundums": "kupofried_corundums",
            "moblin_pheromone_sacks": "pheromone_sacks",
            "rems_tale_chapters_1_stored": "rems_ch1",
            "rems_tale_chapters_2_stored": "rems_ch2",
            "rems_tale_chapters_3_stored": "rems_ch3",
            "rems_tale_chapters_4_stored": "rems_ch4",
            "rems_tale_chapters_5_stored": "rems_ch5",
            "rems_tale_chapters_6_stored": "rems_ch6",
            "rems_tale_chapters_7_stored": "rems_ch7",
            "rems_tale_chapters_8_stored": "rems_ch8",
            "rems_tale_chapters_9_stored": "rems_ch9",
            "rems_tale_chapters_10_stored": "rems_ch10",
            "bloodshed_plans_stored": "bloodshed_plans",
            "umbrage_plans_stored": "umbrage_plans",
            "ritualistic_plans_stored": "ritualistic_plans",
            "tutelary_plans_stored": "tutelary_plans",
            "primacy_plans_stored": "primacy_plans",
            "reclamation_marks": "reclamation_marks",
            "unity_accolades": "unity_accolades",
            "fire_crystals_stored": "fire_crystals",
            "ice_crystals_stored": "ice_crystals",
            "wind_crystals_stored": "wind_crystals",
            "earth_crystals_stored": "earth_crystals",
            "lightning_crystals_stored": "lightning_crystals",
            "water_crystals_stored": "water_crystals",
            "light_crystals_stored": "light_crystals",
            "dark_crystals_stored": "dark_crystals",
            "deeds": "deeds",
        },
        "computed": {
            "daily_tally": 'dailyTally == -1 ? 0 : static_cast<uint16_t>(dailyTally)',
            "unused": '0',
            "traverser_stones": 'charutils::getAvailableTraverserStones(PChar)',
        },
    },
    "0x118": {
        "class": "GP_SERV_COMMAND_CURRENCIES_2",
        "size": 156,
        "fields": [
            ("bayld", "scalar", 0, "int32_t", None, 4),
            ("kinetic_units", "scalar", 4, "uint16_t", None, 2),
            ("coalition_imprimaturs", "scalar", 6, "uint8_t", None, 1),
            ("mystical_canteens", "scalar", 7, "uint8_t", None, 1),
            ("obsidian_fragments", "scalar", 8, "int32_t", None, 4),
            ("lebondopt_wings_stored", "scalar", 12, "uint16_t", None, 2),
            ("pulchridopt_wings_stored", "scalar", 14, "uint16_t", None, 2),
            ("mweya_plasm_corpuscles", "scalar", 16, "int32_t", None, 4),
            ("ghastly_stones_stored", "scalar", 20, "uint8_t", None, 1),
            ("ghastly_stones_plus1_stored", "scalar", 21, "uint8_t", None, 1),
            ("ghastly_stones_plus2_stored", "scalar", 22, "uint8_t", None, 1),
            ("verdigris_stones_stored", "scalar", 23, "uint8_t", None, 1),
            ("verdigris_stones_plus1_stored", "scalar", 24, "uint8_t", None, 1),
            ("verdigris_stones_plus2_stored", "scalar", 25, "uint8_t", None, 1),
            ("wailing_stones_stored", "scalar", 26, "uint8_t", None, 1),
            ("wailing_stones_plus1_stored", "scalar", 27, "uint8_t", None, 1),
            ("wailing_stones_plus2_stored", "scalar", 28, "uint8_t", None, 1),
            ("snowslit_stones_stored", "scalar", 29, "uint8_t", None, 1),
            ("snowslit_stones_plus1_stored", "scalar", 30, "uint8_t", None, 1),
            ("snowslit_stones_plus2_stored", "scalar", 31, "uint8_t", None, 1),
            ("snowtip_stones_stored", "scalar", 32, "uint8_t", None, 1),
            ("snowtip_stones_plus1_stored", "scalar", 33, "uint8_t", None, 1),
            ("snowtip_stones_plus2_stored", "scalar", 34, "uint8_t", None, 1),
            ("snowdim_stones_stored", "scalar", 35, "uint8_t", None, 1),
            ("snowdim_stones_plus1_stored", "scalar", 36, "uint8_t", None, 1),
            ("snowdim_stones_plus2_stored", "scalar", 37, "uint8_t", None, 1),
            ("snoworb_stones_stored", "scalar", 38, "uint8_t", None, 1),
            ("snoworb_stones_plus1_stored", "scalar", 39, "uint8_t", None, 1),
            ("snoworb_stones_plus2_stored", "scalar", 40, "uint8_t", None, 1),
            ("leafslit_stones_stored", "scalar", 41, "uint8_t", None, 1),
            ("leafslit_stones_plus1_stored", "scalar", 42, "uint8_t", None, 1),
            ("leafslit_stones_plus2_stored", "scalar", 43, "uint8_t", None, 1),
            ("leaftip_stones_stored", "scalar", 44, "uint8_t", None, 1),
            ("leaftip_stones_plus1_stored", "scalar", 45, "uint8_t", None, 1),
            ("leaftip_stones_plus2_stored", "scalar", 46, "uint8_t", None, 1),
            ("leafdim_stones_stored", "scalar", 47, "uint8_t", None, 1),
            ("leafdim_stones_plus1_stored", "scalar", 48, "uint8_t", None, 1),
            ("leafdim_stones_plus2_stored", "scalar", 49, "uint8_t", None, 1),
            ("leaforb_stones_stored", "scalar", 50, "uint8_t", None, 1),
            ("leaforb_stones_plus1_stored", "scalar", 51, "uint8_t", None, 1),
            ("leaforb_stones_plus2_stored", "scalar", 52, "uint8_t", None, 1),
            ("duskslit_stones_stored", "scalar", 53, "uint8_t", None, 1),
            ("duskslit_stones_plus1_stored", "scalar", 54, "uint8_t", None, 1),
            ("duskslit_stones_plus2_stored", "scalar", 55, "uint8_t", None, 1),
            ("dusktip_stones_stored", "scalar", 56, "uint8_t", None, 1),
            ("dusktip_stones_plus1_stored", "scalar", 57, "uint8_t", None, 1),
            ("dusktip_stones_plus2_stored", "scalar", 58, "uint8_t", None, 1),
            ("duskdim_stones_stored", "scalar", 59, "uint8_t", None, 1),
            ("duskdim_stones_plus1_stored", "scalar", 60, "uint8_t", None, 1),
            ("duskdim_stones_plus2_stored", "scalar", 61, "uint8_t", None, 1),
            ("duskorb_stones_stored", "scalar", 62, "uint8_t", None, 1),
            ("duskorb_stones_plus1_stored", "scalar", 63, "uint8_t", None, 1),
            ("duskorb_stones_plus2_stored", "scalar", 64, "uint8_t", None, 1),
            ("pellucid_stones_stored", "scalar", 65, "uint8_t", None, 1),
            ("fern_stones_stored", "scalar", 66, "uint8_t", None, 1),
            ("taupe_stones_stored", "scalar", 67, "uint8_t", None, 1),
            ("mellidopt_wings_stored", "scalar", 68, "uint16_t", None, 2),
            ("escha_beads", "scalar", 70, "uint16_t", None, 2),
            ("escha_silt", "scalar", 72, "int32_t", None, 4),
            ("potpourri", "scalar", 76, "int32_t", None, 4),
            ("hallmarks", "scalar", 80, "int32_t", None, 4),
            ("total_hallmarks", "scalar", 84, "int32_t", None, 4),
            ("badges_of_gallantry", "scalar", 88, "int32_t", None, 4),
            ("crafter_points", "scalar", 92, "int32_t", None, 4),
            ("fire_crystals_set", "scalar", 96, "uint8_t", None, 1),
            ("ice_crystals_set", "scalar", 97, "uint8_t", None, 1),
            ("wind_crystals_set", "scalar", 98, "uint8_t", None, 1),
            ("earth_crystals_set", "scalar", 99, "uint8_t", None, 1),
            ("lightning_crystals_set", "scalar", 100, "uint8_t", None, 1),
            ("water_crystals_set", "scalar", 101, "uint8_t", None, 1),
            ("light_crystals_set", "scalar", 102, "uint8_t", None, 1),
            ("dark_crystals_set", "scalar", 103, "uint8_t", None, 1),
            ("mc_i_sr01s_set", "scalar", 104, "uint8_t", None, 1),
            ("mc_i_sr02s_set", "scalar", 105, "uint8_t", None, 1),
            ("mc_i_sr03s_set", "scalar", 106, "uint8_t", None, 1),
            ("liquefactions_spheres_set", "scalar", 107, "uint8_t", None, 1),
            ("induration_spheres_set", "scalar", 108, "uint8_t", None, 1),
            ("dentonation_spheres_set", "scalar", 109, "uint8_t", None, 1),
            ("scission_spheres_set", "scalar", 110, "uint8_t", None, 1),
            ("impaction_spheres_set", "scalar", 111, "uint8_t", None, 1),
            ("reverberation_spheres_set", "scalar", 112, "uint8_t", None, 1),
            ("transfixion_spheres_set", "scalar", 113, "uint8_t", None, 1),
            ("compression_spheres_set", "scalar", 114, "uint8_t", None, 1),
            ("fusion_spheres_set", "scalar", 115, "uint8_t", None, 1),
            ("distortion_spheres_set", "scalar", 116, "uint8_t", None, 1),
            ("fragmentation_spheres_set", "scalar", 117, "uint8_t", None, 1),
            ("gravitation_spheres_set", "scalar", 118, "uint8_t", None, 1),
            ("light_spheres_set", "scalar", 119, "uint8_t", None, 1),
            ("darkness_spheres_set", "scalar", 120, "uint8_t", None, 1),
            ("padding00", "array", 121, "uint8_t", 3, 1),
            ("silver_aman_vouchers_stored", "scalar", 124, "int32_t", None, 4),
            ("domain_points", "scalar", 128, "int32_t", None, 4),
            ("domain_points_earned_today", "scalar", 132, "int32_t", None, 4),
            ("mog_segments", "scalar", 136, "int32_t", None, 4),
            ("gallimaufry", "scalar", 140, "int32_t", None, 4),
            ("is_accolades", "scalar", 144, "uint16_t", None, 2),
            ("padding02", "scalar", 146, "uint16_t", None, 2),
            ("temenos_units", "scalar", 148, "int32_t", None, 4),
            ("apollyon_units", "scalar", 152, "int32_t", None, 4),
        ],
        "columns": {
            "bayld": "bayld",
            "kinetic_units": "kinetic_unit",
            "coalition_imprimaturs": "imprimaturs",
            "mystical_canteens": "mystical_canteen",
            "obsidian_fragments": "obsidian_fragment",
            "lebondopt_wings_stored": "lebondopt_wing",
            "pulchridopt_wings_stored": "pulchridopt_wing",
            "mweya_plasm_corpuscles": "mweya_plasm",
            "ghastly_stones_stored": "ghastly_stone",
            "ghastly_stones_plus1_stored": "ghastly_stone_1",
            "ghastly_stones_plus2_stored": "ghastly_stone_2",
            "verdigris_stones_stored": "verdigris_stone",
            "verdigris_stones_plus1_stored": "verdigris_stone_1",
            "verdigris_stones_plus2_stored": "verdigris_stone_2",
            "wailing_stones_stored": "wailing_stone",
            "wailing_stones_plus1_stored": "wailing_stone_1",
            "wailing_stones_plus2_stored": "wailing_stone_2",
            "snowslit_stones_stored": "snowslit_stone",
            "snowslit_stones_plus1_stored": "snowslit_stone_1",
            "snowslit_stones_plus2_stored": "snowslit_stone_2",
            "snowtip_stones_stored": "snowtip_stone",
            "snowtip_stones_plus1_stored": "snowtip_stone_1",
            "snowtip_stones_plus2_stored": "snowtip_stone_2",
            "snowdim_stones_stored": "snowdim_stone",
            "snowdim_stones_plus1_stored": "snowdim_stone_1",
            "snowdim_stones_plus2_stored": "snowdim_stone_2",
            "snoworb_stones_stored": "snoworb_stone",
            "snoworb_stones_plus1_stored": "snoworb_stone_1",
            "snoworb_stones_plus2_stored": "snoworb_stone_2",
            "leafslit_stones_stored": "leafslit_stone",
            "leafslit_stones_plus1_stored": "leafslit_stone_1",
            "leafslit_stones_plus2_stored": "leafslit_stone_2",
            "leaftip_stones_stored": "leaftip_stone",
            "leaftip_stones_plus1_stored": "leaftip_stone_1",
            "leaftip_stones_plus2_stored": "leaftip_stone_2",
            "leafdim_stones_stored": "leafdim_stone",
            "leafdim_stones_plus1_stored": "leafdim_stone_1",
            "leafdim_stones_plus2_stored": "leafdim_stone_2",
            "leaforb_stones_stored": "leaforb_stone",
            "leaforb_stones_plus1_stored": "leaforb_stone_1",
            "leaforb_stones_plus2_stored": "leaforb_stone_2",
            "duskslit_stones_stored": "duskslit_stone",
            "duskslit_stones_plus1_stored": "duskslit_stone_1",
            "duskslit_stones_plus2_stored": "duskslit_stone_2",
            "dusktip_stones_stored": "dusktip_stone",
            "dusktip_stones_plus1_stored": "dusktip_stone_1",
            "dusktip_stones_plus2_stored": "dusktip_stone_2",
            "duskdim_stones_stored": "duskdim_stone",
            "duskdim_stones_plus1_stored": "duskdim_stone_1",
            "duskdim_stones_plus2_stored": "duskdim_stone_2",
            "duskorb_stones_stored": "duskorb_stone",
            "duskorb_stones_plus1_stored": "duskorb_stone_1",
            "duskorb_stones_plus2_stored": "duskorb_stone_2",
            "pellucid_stones_stored": "pellucid_stone",
            "fern_stones_stored": "fern_stone",
            "taupe_stones_stored": "taupe_stone",
            "escha_beads": "escha_beads",
            "escha_silt": "escha_silt",
            "potpourri": "potpourri",
            "hallmarks": "current_hallmarks",
            "total_hallmarks": "total_hallmarks",
            "badges_of_gallantry": "gallantry",
            "crafter_points": "crafter_points",
            "fire_crystals_set": "fire_crystal_set",
            "ice_crystals_set": "ice_crystal_set",
            "wind_crystals_set": "wind_crystal_set",
            "earth_crystals_set": "earth_crystal_set",
            "lightning_crystals_set": "lightning_crystal_set",
            "water_crystals_set": "water_crystal_set",
            "light_crystals_set": "light_crystal_set",
            "dark_crystals_set": "dark_crystal_set",
            "mc_i_sr01s_set": "mc_s_sr01_set",
            "mc_i_sr02s_set": "mc_s_sr02_set",
            "mc_i_sr03s_set": "mc_s_sr03_set",
            "liquefactions_spheres_set": "liquefaction_spheres_set",
            "induration_spheres_set": "induration_spheres_set",
            "dentonation_spheres_set": "detonation_spheres_set",
            "scission_spheres_set": "scission_spheres_set",
            "impaction_spheres_set": "impaction_spheres_set",
            "reverberation_spheres_set": "reverberation_spheres_set",
            "transfixion_spheres_set": "transfixion_spheres_set",
            "compression_spheres_set": "compression_spheres_set",
            "fusion_spheres_set": "fusion_spheres_set",
            "distortion_spheres_set": "distortion_spheres_set",
            "fragmentation_spheres_set": "fragmentation_spheres_set",
            "gravitation_spheres_set": "gravitation_spheres_set",
            "light_spheres_set": "light_spheres_set",
            "darkness_spheres_set": "darkness_spheres_set",
            "silver_aman_vouchers_stored": "silver_aman_voucher",
            "domain_points": "domain_points",
            "domain_points_earned_today": "domain_points_daily",
            "mog_segments": "mog_segments",
            "gallimaufry": "gallimaufry",
            "is_accolades": "is_accolades",
            "temenos_units": "temenos_units",
            "apollyon_units": "apollyon_units",
        },
        "computed": {
            "mellidopt_wings_stored": '0',
        },
    },
}

# Abilities LSB gates on a `learned` bit (addType & ADDTYPE_LEARNED)
# in char_abilities. Everything else is granted by job and level, so a
# bit set for it is inert -- these are the only ids worth importing.
LEARNED_ABILITIES = {
    98: "fighters_roll",
    99: "monks_roll",
    100: "healers_roll",
    101: "wizards_roll",
    102: "warlocks_roll",
    103: "rogues_roll",
    104: "gallants_roll",
    105: "chaos_roll",
    106: "beast_roll",
    107: "choral_roll",
    108: "hunters_roll",
    109: "samurai_roll",
    110: "ninja_roll",
    111: "drachen_roll",
    112: "evokers_roll",
    113: "maguss_roll",
    114: "corsairs_roll",
    115: "puppet_roll",
    116: "dancers_roll",
    117: "scholars_roll",
    118: "bolters_roll",
    119: "casters_roll",
    120: "coursers_roll",
    121: "blitzers_roll",
    122: "tacticians_roll",
    302: "allies_roll",
    303: "misers_roll",
    304: "companions_roll",
    305: "avengers_roll",
    390: "naturalists_roll",
    391: "runeists_roll",
}

# weapon skill id -> wsUnlockId, the BIT POSITION in chars.weaponskills
# (xi::bitset<64>). These are two different id spaces: Decimation is
# weapon skill 72 and unlock id 5. Only unlockable weapon skills appear;
# unlock_id 0 is LSB's sentinel for 'not unlockable' and bit 0 is unused.
WS_UNLOCKS = {
    9: 1,
    11: 15,
    12: 16,
    14: 35,
    15: 60,
    25: 2,
    27: 17,
    28: 18,
    29: 19,
    31: 36,
    42: 3,
    44: 20,
    45: 21,
    46: 22,
    56: 4,
    59: 38,
    60: 57,
    61: 49,
    72: 5,
    74: 23,
    76: 39,
    77: 58,
    88: 6,
    90: 24,
    92: 40,
    93: 63,
    104: 7,
    106: 25,
    108: 41,
    109: 52,
    120: 8,
    122: 26,
    124: 42,
    125: 61,
    136: 9,
    138: 27,
    140: 43,
    141: 51,
    152: 10,
    154: 28,
    156: 44,
    157: 62,
    169: 11,
    171: 29,
    173: 45,
    174: 55,
    184: 12,
    186: 30,
    187: 31,
    188: 32,
    190: 46,
    191: 59,
    199: 13,
    202: 47,
    203: 50,
    215: 14,
    217: 33,
    218: 34,
    220: 48,
    221: 54,
    224: 53,
    225: 37,
    226: 56,
}

# 0x056 quest/mission log: the enums that say which block a `Port` is,
# and the byte layout of the structures chars.quests / .missions /
# .assault / .campaign hold. The PACKING is code, not data, and lives
# in ffxi_import_core -- these are only the numbers it needs.
QUEST_LOG = {
    "Sandoria": 0,
    "Bastok": 1,
    "Windurst": 2,
    "Jeuno": 3,
    "OtherAreas": 4,
    "Outlands": 5,
    "AhtUrghan": 6,
    "CrystalWar": 7,
    "Abyssea": 8,
    "Adoulin": 9,
    "Coalition": 10,
}

QUEST_OFFER = {
    "Sandoria": 80,
    "Bastok": 88,
    "Windurst": 96,
    "Jeuno": 104,
    "OtherAreas": 112,
    "Outlands": 120,
    "AhtUrghan": 128,
    "CrystalWar": 136,
    "Abyssea": 224,
    "Adoulin": 240,
    "Coalition": 256,
}

QUEST_COMPLETE = {
    "Sandoria": 144,
    "Bastok": 152,
    "Windurst": 160,
    "Jeuno": 168,
    "OtherAreas": 176,
    "Outlands": 184,
    "AhtUrghan": 192,
    "CrystalWar": 200,
    "Abyssea": 232,
    "Adoulin": 248,
    "Coalition": 264,
}

MISSION_LOG = {
    "Sandoria": 0,
    "Bastok": 1,
    "Windurst": 2,
    "Zilart": 3,
    "ToAU": 4,
    "WoTG": 5,
    "CoP": 6,
    "Assault": 7,
    "Campaign": 8,
    "ACP": 9,
    "AMK": 10,
    "ASA": 11,
    "SoA": 12,
    "RoV": 13,
}

MISSION_COMPLETE = {
    "Campaign1": 48,
    "Campaign2": 56,
    "Nations": 208,
    "ToAU_WoTG": 216,
}

# struct name -> (size_in_bytes, [(member, ctype, count, offset)])
LOG_STRUCTS = {
    "questlog_t": (64, [
        ("current", "uint8", 32, 0),
        ("complete", "uint8", 32, 32),
    ]),
    "missionlog_t": (70, [
        ("current", "uint16", 1, 0),
        ("statusUpper", "uint16", 1, 2),
        ("statusLower", "uint16", 1, 4),
        ("complete", "bool", 64, 6),
    ]),
    "assaultlog_t": (130, [
        ("current", "uint16", 1, 0),
        ("complete", "bool", 128, 2),
    ]),
    "campaignlog_t": (514, [
        ("current", "uint16", 1, 0),
        ("complete", "bool", 512, 2),
    ]),
}

# how many of each structure the corresponding chars blob holds
LOG_COUNTS = {
    "questlog_t": 11,
    "missionlog_t": 15,
    "assaultlog_t": 1,
    "campaignlog_t": 1,
}

# The client's homepoint INDEX -> where LSB puts you when you go home.
# index: (x, y, z, rot, zone_id, zone_name), from
# scripts/globals/homepoint.lua with xi.zone.* resolved via zone.yaml.
HOMEPOINTS = {
    0: (-85.554, 1.0, -64.554, 45, 230, "southern_san_doria"),
    1: (44.1, 2.0, -34.5, 170, 230, "southern_san_doria"),
    2: (140.5, -2.0, 121.0, 0, 230, "southern_san_doria"),
    3: (-178.0, 4.0, 71.0, 0, 231, "northern_san_doria"),
    4: (10.0, -0.2, 95.0, 0, 231, "northern_san_doria"),
    5: (70.0, -0.2, 10.0, 0, 231, "northern_san_doria"),
    6: (-38.0, -4.0, -63.0, 0, 232, "port_san_doria"),
    7: (48.0, -12.0, -105.0, 0, 232, "port_san_doria"),
    8: (-6.0, -13.0, -150.0, 0, 232, "port_san_doria"),
    9: (39.0, 0.0, -43.0, 0, 234, "bastok_mines"),
    10: (118.0, 1.0, -58.0, 0, 234, "bastok_mines"),
    11: (-342.0, -10.0, -154.0, 0, 235, "bastok_markets"),
    12: (-328.0, -12.0, -33.0, 0, 235, "bastok_markets"),
    13: (-189.0, -8.0, 26.0, 0, 235, "bastok_markets"),
    14: (124.0, 8.0, 7.0, 0, 236, "port_bastok"),
    15: (42.0, 8.5, -244.0, 0, 236, "port_bastok"),
    16: (46.0, -14.0, -19.0, 0, 237, "metalworks"),
    17: (-32.0, -5.0, 132.0, 0, 238, "windurst_waters"),
    18: (138.5, 0.0, -14.0, 0, 238, "windurst_waters"),
    19: (-72.0, -5.0, 125.0, 0, 239, "windurst_walls"),
    20: (-212.0, 0.0, -99.0, 0, 239, "windurst_walls"),
    21: (31.0, -6.5, -40.0, 0, 239, "windurst_walls"),
    22: (-188.0, -4.0, 101.0, 0, 240, "port_windurst"),
    23: (-207.0, -8.0, 210.0, 0, 240, "port_windurst"),
    24: (180.0, -12.0, 226.0, 0, 240, "port_windurst"),
    25: (9.0, -2.0, 0.0, 0, 241, "windurst_woods"),
    26: (107.0, -5.0, -56.0, 0, 241, "windurst_woods"),
    27: (-92.0, -5.0, 62.0, 0, 241, "windurst_woods"),
    28: (74.0, -7.0, -139.0, 0, 241, "windurst_woods"),
    29: (-6.0, 3.0, 0.0, 0, 243, "rulude_gardens"),
    30: (53.0, 9.0, -57.0, 0, 243, "rulude_gardens"),
    31: (-67.0, 6.0, -25.0, 1, 243, "rulude_gardens"),
    32: (-99.0, 0.0, 167.0, 0, 244, "upper_jeuno"),
    33: (32.0, -1.0, -44.0, 0, 244, "upper_jeuno"),
    34: (-52.0, 1.0, 16.0, 0, 244, "upper_jeuno"),
    35: (-99.0, 0.0, -183.0, 0, 245, "lower_jeuno"),
    36: (18.0, -1.0, 54.0, 0, 245, "lower_jeuno"),
    37: (37.0, 0.0, 9.0, 0, 246, "port_jeuno"),
    38: (-155.0, -1.0, -4.0, 0, 246, "port_jeuno"),
    39: (78.0, -13.0, -94.0, 0, 250, "kazham"),
    40: (-13.0, -15.0, 87.0, 0, 249, "mhaura"),
    41: (-27.0, 0.0, -47.0, 0, 252, "norg"),
    42: (-29.0, 0.0, -76.0, 0, 247, "rabao"),
    43: (36.0, -11.0, 35.0, 0, 248, "selbina"),
    44: (-84.0, 4.0, -32.0, 128, 256, "western_adoulin"),
    45: (-51.0, 0.0, 59.0, 128, 257, "eastern_adoulin"),
    46: (-107.0, 3.0, 295.0, 128, 261, "ceizak_battlegrounds"),
    47: (-193.0, -0.5, -252.0, 128, 262, "foret_de_hennetiel"),
    48: (-415.0, -63.2, 409.0, 106, 265, "morimar_basalt_fields"),
    49: (-420.0, 0.0, -62.0, 64, 263, "yorcia_weald"),
    50: (-23.0, 0.0, 174.0, 0, 266, "marjami_ravine"),
    51: (210.0, 20.299, 315.0, 192, 267, "kamihr_drifts"),
    52: (434.0, -40.0, 171.0, 0, 142, "yughott_grotto"),
    53: (109.0, -38.0, -147.0, 0, 143, "palborough_mines"),
    54: (-132.0, -3.0, -303.0, 0, 145, "giddeus"),
    55: (243.0, -24.0, 62.0, 0, 204, "feiyin"),
    56: (-984.0, 17.0, -289.0, 0, 208, "quicksand_caves"),
    57: (-80.0, 46.0, 62.0, 0, 160, "den_of_rancor"),
    58: (-554.0, -70.0, 66.0, 0, 162, "castle_zvahl_keep"),
    59: (5.0, -42.0, 526.0, 0, 130, "ruaun_gardens"),
    60: (-312.0, -42.0, -422.0, 0, 130, "ruaun_gardens"),
    61: (-499.0, -42.0, 167.0, 0, 130, "ruaun_gardens"),
    62: (500.0, -42.0, 158.0, 0, 130, "ruaun_gardens"),
    63: (305.0, -42.0, -427.0, 0, 130, "ruaun_gardens"),
    64: (-1.0, -28.0, 107.0, 0, 26, "tavnazian_safehold"),
    65: (-21.0, 0.0, -21.0, 0, 50, "aht_urhgan_whitegate"),
    66: (-20.0, 0.0, -25.0, 0, 53, "nashmau"),
    67: (0.0, 0.0, 0.0, 0, 48, "al_zahbi"),
    68: (-85.0, 1.0, -66.0, 0, 80, "southern_san_doria_s"),
    69: (-293.0, -10.0, -102.0, 0, 87, "bastok_markets_s"),
    70: (-32.0, -5.0, 131.0, 0, 94, "windurst_waters_s"),
    71: (-365.0, -176.5, -36.0, 0, 158, "upper_delkfutts_tower"),
    72: (-13.0, 48.0, 61.0, 0, 178, "the_shrine_of_ruavitau"),
    73: (-520.0, -18.0, 505.0, 127, 29, "riverne_site_b01"),
    74: (-98.0, -10.0, -493.0, 192, 52, "bhaflau_thickets"),
    75: (-449.0, 13.0, -497.0, 0, 79, "caedarva_mire"),
    76: (64.0, -196.0, 181.0, 0, 5, "uleguerand_range"),
    77: (380.0, 23.0, -62.0, 0, 5, "uleguerand_range"),
    78: (424.0, -32.0, 221.0, 0, 5, "uleguerand_range"),
    79: (64.0, -96.0, 461.0, 0, 5, "uleguerand_range"),
    80: (-220.0, -1.0, -62.0, 0, 5, "uleguerand_range"),
    81: (-200.0, -10.0, 342.0, 0, 7, "attohwa_chasm"),
    82: (-58.0, 40.0, 14.0, 64, 9, "psoxja"),
    83: (445.0, 27.0, -22.0, 0, 12, "newton_movalpolos"),
    84: (189.0, 0.0, 362.0, 0, 30, "riverne_site_a01"),
    85: (7.0, 0.0, 709.0, 192, 33, "altaieu"),
    86: (-532.0, 0.0, 447.0, 128, 33, "altaieu"),
    87: (569.0, 0.0, 410.0, 192, 33, "altaieu"),
    88: (-12.0, 0.0, -288.0, 192, 34, "grand_palace_of_huxzoi"),
    89: (-426.0, 0.0, 368.0, 224, 35, "the_garden_of_ruhmet"),
    90: (-540.844, -4.0, 70.809, 74, 61, "mount_zhayolm"),
    91: (-303.0, -8.0, 526.0, 0, 113, "cape_teriggan"),
    92: (88.0, -15.0, -217.0, 0, 153, "the_boyahda_tree"),
    93: (182.0, 34.0, -62.0, 223, 160, "den_of_rancor"),
    94: (102.0, 0.0, 269.0, 191, 204, "feiyin"),
    95: (-63.0, 50.0, 81.0, 192, 205, "ifrits_cauldron"),
    96: (573.0, 9.0, -500.0, 0, 208, "quicksand_caves"),
    97: (-165.0, -1.0, 12.0, 65, 230, "southern_san_doria"),
    98: (-132.0, 12.0, 194.0, 170, 231, "northern_san_doria"),
    99: (87.0, 7.0, 1.0, 0, 234, "bastok_mines"),
    100: (-192.0, -6.0, -69.0, 0, 235, "bastok_markets"),
    101: (-127.0, -6.0, 8.0, 206, 236, "port_bastok"),
    102: (-76.0, 2.0, 3.0, 124, 237, "metalworks"),
    103: (5.0, -4.0, -175.0, 130, 238, "windurst_waters"),
    104: (-65.0, -5.0, 54.0, 127, 252, "norg"),
    105: (-21.0, 8.0, 110.0, 64, 247, "rabao"),
    106: (130.0, 0.0, -16.0, 0, 50, "aht_urhgan_whitegate"),
    107: (-108.0, -6.0, 108.0, 192, 50, "aht_urhgan_whitegate"),
    108: (-99.0, 0.0, -68.0, 0, 50, "aht_urhgan_whitegate"),
    109: (32.0, 0.0, -164.0, 32, 256, "western_adoulin"),
    110: (-51.0, 0.0, -96.0, 96, 257, "eastern_adoulin"),
    111: (223.0, -13.0, -254.0, 0, 137, "xarcabard_s"),
    112: (5.539, -0.434, 8.133, 73, 281, "leafallia"),
    113: (-554.0, -70.0, 66.0, 128, 155, "castle_zvahl_keep_s"),
    114: (-212.0, -21.0, 93.0, 64, 126, "qufim_island"),
    115: (-257.5, 24.0, 82.0, 192, 169, "toraimarai_canal"),
    116: (757.0, 120.0, 17.5, 128, 276, "rakaznar_inner_court"),
    117: (-65.0, -17.5, 563.0, 224, 25, "misareaux_coast"),
    118: (-92.0, -2.0, 54.0, 155, 238, "windurst_waters"),
    119: (-43.5, 0.0, -145.0, 0, 241, "windurst_woods"),
    120: (14.0, -9.96, -5.0, 0, 26, "tavnazian_safehold"),
    121: (73.59, -36.149, 38.87, 0, 26, "tavnazian_safehold"),
}
